# @baseUrl = https://c9rd6ln3mk.execute-api.us-east-1.amazonaws.com/default
# @baseUrl = http://192.168.1.237:3333
# @baseUrl = http://localhost:3333

# @baseUrl = http://172.20.10.2:3333
# @baseUrl = http://localhost:3000/dev

# @baseUrl = https://hubdash.space
@baseUrl = https://api.hubdash.space

# @authToken = {{authenticate.response.body.access_token}}

# @name test_route
GET {{baseUrl}}/test
Content-Type: application/json

###

# @name create_account
POST {{baseUrl}}/parcel-forwarding/register
Content-Type: application/json

{
  "name": "Voabox",
  "initials": "Vbs",
  "email": "voabox@voabox.com",
  "password": "Abc123456@"
}

###

# @name authenticate
POST {{baseUrl}}/sessions/login
Content-Type: application/json

{
  "email": "voabox@voabox.com",
  "password": "Abc123456@"
}

###

# @name logout
POST {{baseUrl}}/sessions/logout
Content-Type: application/json



###

# @name verify_token2
GET {{baseUrl}}/protected
Content-Type: application/json

###

# @name create_check_in
POST {{baseUrl}}/check-in
Content-Type: application/json

{
  "customerId": "00822b6c-ff53-4702-b21e-d8bfe59a3c46",
  "details": "Everything is ok with the items",
  "weight": 6,
  "attachmentsIds": ["03ec45d5-834d-442f-a7e1-5679b1d80e17"]
}

###

# @name fetch_recent_check_ins
GET {{baseUrl}}/check-ins?page=1
Content-Type: application/json

###

# @name get_customer_by_hub_id
GET {{baseUrl}}/customer/1
Content-Type: application/json

###

# @name upload_file
POST {{baseUrl}}/attachments
Content-Type: multipart/form-data; boundary=myBoundary

--myBoundary
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/jpg

< ./image.png
--myBoundary--

###

# @name send-reset-password-email
POST {{baseUrl}}/send-reset-password-email
Content-Type: application/json

{
  "email": "alonsofts@gmail.com"
}

###

# @name verify-reset-password-token
POST {{baseUrl}}/verify-reset-password-token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsb25zb2Z0c0BnbWFpbC5jb20iLCJpYXQiOjE3MjYzNDc0NzcsImV4cCI6MTcyNjM1MTA3N30.pD9FuvzzHroGsWck3Nu8iwSiS15IcTTS6ahOPwuYpMU"
}

###

# @name reset-password
POST {{baseUrl}}/reset-password
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsb25zb2Z0c0BnbWFpbC5jb20iLCJpYXQiOjE3MjY0MzQ1NTksImV4cCI6MTcyNjQzODE1OX0.XlubTD-BpCdgyN_kUDNohVnD3IuNsalJ7YhAjrPbTbM",
  "newPassword": "Abc123456@"
}

