@baseUrl = https://c9rd6ln3mk.execute-api.us-east-1.amazonaws.com/default
@authToken = {{authenticate.response.body.access_token}}

# @name test_route
GET {{baseUrl}}/test
Content-Type: application/json

###

# @name create_account
POST {{baseUrl}}/parcel-forwarding/register
Content-Type: application/json

{
  "name": "Voabox",
  "initials": "Vbs",
  "email": "contato1234@voabox.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "Lorena49@hotmail.com",
  "password": "123456"
}

###

# @name create_check_in
POST {{baseUrl}}/check-in
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "customerId": "2017bf2b-0b61-4d9f-b016-e43b9ca40123",
  "details": "Everything is ok with the items",
  "weight": "6",
  "atattachmentsIds": ["2017bf2b-0b61-4d9f-b016-e43b9ca40123"]
}

###

# @name fetch_recent_check_ins
GET {{baseUrl}}/check-ins?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_customer_by_hub_id
GET {{baseUrl}}/customer/3
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name upload_file
POST {{baseUrl}}/attachments
Content-Type: multipart/form-data; boundary=myBoundary

--myBoundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./image.png

