@baseUrl = http://localhost:3000/dev
@authToken = {{authenticate.response.body.access_token}}

# @name test_route
POST {{baseUrl}}/test
Content-Type: application/json

{
  "message": "This is a test message"
}

###

# @name create_account
POST {{baseUrl}}/parcel-forwarding/register
Content-Type: application/json

{
  "name": "Voabox",
  "initials": "Vbs",
  "email": "contato10@voabox.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "pf1@example.com",
  "password": "123456"
}

###

# @name create_check_in
POST {{baseUrl}}/check-in
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "customerId": "c2198e4b-1b6b-4bec-9023-6bb1ac841671",
  "details": "Everything is ok with the items",
  "weight": "6"
  "atattachmentsIds": ['oiwiwow']
}

###

# @name fetch_recent_check_ins
GET {{baseUrl}}/check-ins?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}