name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: hub-postgres-db
        options: >-
          --health-cmd="pg_isready -U postgres -d hub-postgres-db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Start Docker Compose services
        run: docker-compose up -d
        env:
          DATABASE_URL: postgresql://postgres:docker@localhost:5432/hub-postgres-db

      - name: Wait for Postgres to be ready
        run: until docker-compose exec postgres pg_isready -U postgres -d hub-postgres-db; do sleep 1; done

      - name: Run Prisma migrations
        run: docker-compose exec prisma npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:docker@localhost:5432/hub-postgres-db

      - name: Run tests
        run: npm run test:e2e

      - name: Stop Docker Compose services
        if: always()
        run: docker-compose down

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results # Adjust the path as necessary
